[[capacity-development-objectives]]
== Capacity development objectives 

Capacity is broadly defined by the Organization for Economic Cooperation and Development (OECD) as _“the ability of individuals, institutions, and societies to perform functions, solve problems and set and achieve objectives in a sustainable manner”_. Capacity development refers to _“the processes whereby people, organizations, and society as a whole unleash, strengthen, create, adapt and maintain capacity over time”_. These definitions are widely used in the field of international cooperation, and are applicable to GBIF.

GBIF’s https://www.gbif.org/strategic-plan[strategic framework 2023-2027^] sets out the global vision and mission, together with four strategic priority areas to achieve these (see 1.1). Capacity development, while emphasized especially in priority area 3,  will contribute to GBIF’s success across all areas of the strategic framework.

[[box-1]]
=== GBIF’s Vision, Mission and Priority areas

****
*GBIF’s vision*:  A world in which the best possible biodiversity data underpins research, policy, and decisions.

*GBIF mission*: To mobilize the data, skills, and technologies needed to make comprehensive biodiversity information freely available for science and decisions addressing biodiversity loss and sustainable development.

Priority area 1: Science and Research

Priority area 2: Policy and Partnerships

Priority area 3: Community and Capacity

Priority area 4: Infrastructure and Data Products
****

GBIF has defined values within the strategic framework that underpin all efforts to advance our work, and apply to the Secretariat, to the global nodes network, to participants, to data publishing institutions, and to data users, that together embody the global GBIF community. These values guide how capacity development actions are developed and should be implemented at all levels, as demonstrated through examples (see 1.2).

[[box-2]]
=== GBIF Values and how they apply to capacity development

****
*Trust and Transparency*: Expectations that all decisions and processes are open; that data is properly attributed and of the highest-possible quality; and that infrastructures are robust, documented and persistent.

Examples

* All opportunities will be shared through open calls with transparent selection processes based on predefined criteria and involving experts from the wider community. 
* We provide guidance and support where necessary to grant holding institutions to develop project management capacity based on transparent processes. 
* All contributions to capacity development actions will be attributed to the individuals, institutions, nodes and regions involved.
****

****
*Collaboration and Collective Benefit*: A recognition that only through a spirit of cooperation can we fulfil GBIF’s mission by sharing skills, data, tools and experiences, avoiding duplication, and growing a global community of practice GBIF’s capacity development approach will be based on facilitating the exchange of experience, data and technology between partners.

Examples

* Training actions engage local trainers and mentors when possible, encourage replication and ongoing knowledge-sharing, and make use of training materials are designed with reuse and adaptation in mind. 
* We work through partnerships to support the development of skills that are either fundamental to, or extensions of, the core skills in which GBIF develops capacity.
The endorsement model through our existing network of nodes is used throughout calls for capacity development actions to encourage national and regional coordination. 
* We give full visibility to partners and encourage them to give visibility to GBIF in return through roles, branding policy, and mutual credit.
****

****
*Diversity and Inclusiveness*: A commitment to engage and welcome people of all nationalities, cultures, genders and backgrounds while recognizing all contributions to our global community.

Examples

* We recognize and focus on capacity development and community engagement in regions and countries where we have known participation and data gaps.
* A https://www.gbif.org/code-of-conduct[code of conduct^] is promoted through all capacity development activities.
* Selection criteria that encourage diversity are included in all processes.
* We facilitate and encourage translation and local adaptation of all training materials and documentation to support their uptake.
* Capacity development actions contribute to outreach, for example through the participation of observers and new institutions and countries in actions at all levels, and promote full participation in GBIF governance on the long term for the sustainability of GBIF as a global infrastructure and network.
* We support capacity development through regional groupings that build cohesion through shared priorities, languages, biodiversity.
****

****
*Innovation*: An ambition to lead by example in advancing open science and data services and in adopting novel techniques for collaboration and learning, recognizing that simplicity is often the best means of reaching our goals.

Examples

* As much as possible, we promote the use of open-source software and tools in all capacity development actions and avoid creating any dependencies on products without open licences.
* We investigate and adopt new tools and processes to support capacity development, including guided capacity self-assessments and recognition of skills through digital badges.
****

****
*Integrity*: An assurance that professional norms and scientific integrity are respected; and that data-sharing safeguards the rights of indigenous peoples and local communities as well as potential risks to sensitive species.

Examples

* Capacity development actions align with data mobilization guidelines that are continually updated to promote appropriate data sharing, attribution, licensing and risk awareness.
* Capacity development actions are led by the institutions or countries that are to benefit from the actions, ensuring that they are aligned with self-assessed capacity needs, and make use of local expertise and systems.
****

The main objectives of capacity development in GBIF, covering both technical and functional capacities, are to develop the capacity to mobilize biodiversity data through GBIF, and the capacity to use GBIF-mediated data in research and decision making.

=== Developing the capacity to mobilize biodiversity data through GBIF 

<>The ability to manage, standardize and publish biodiversity data

This is essential to reducing knowledge gaps and ensuring a stable foundation for data mobilization through the network (priority areas 1 and 3). As GBIF evolves and adapts data standards and models (priority area 4), further capacity development will be needed to support the uptake of new data publishing methods by its current network, as well as to integrate new data publishing communities. Growing awareness at the policy level of the importance of enhanced access to primary biodiversity data, for example to support implementation and monitoring of the Kunming-Montreal Global Biodiversity Framework (priority area 2),  strengthens the justification for developing capacity to mobilize data. 

Progress towards this objective will be demonstrated in the growth and continued activity of the community of data publishing institutions. Enriching GBIF’s data model will increase the diversity among institutions in the data publishing community. Ultimately, progress will be reflected in the completeness and richness of the data being published.

Institutional capacity for data management varies widely among the different institutions that produce and hold biodiversity data. Capacity varies between different regions of the world, and also between different types and sizes of biodiversity-related institutions. Supportive international policy frameworks can strengthen the enabling environment for institutions within and beyond GBIF’s current network to provide open access to their biodiversity data. While data publishing in GBIF is on the institutional level, it depends on the skills and engagement of individuals within the institutions, as well as capacity at the level of the Participant nodes that assist with engagement, provide endorsement, and often offer technical support. 

As a network of networks, Participant-led efforts to promote data mobilization and support the development of institutional capacity within their countries and networks remain essential to allow capacity support to scale towards a truly global network. This necessitates continued support for capacity development within an expanding network of Participant nodes.

Efforts to design and implement capacity development actions that target the levelling-up of institutional capacity in currently under-represented regions and among under-represented data publishing communities should continue to be a priority for the GBIF network. Such efforts should reinforce the capacity of existing Participant nodes - and encourage the development of new nodes - to ensure sustainable capacity support to the growing data publishing network. Regional support teams extend support beyond the nodes network to enable new institutions from non-Participant countries to engage in data mobilization and use, growing the community of practice that forms the foundation for formal Participation in the future.

=== Developing the capacity to use GBIF-mediated biodiversity data

<>The ability to analyse and use biodiversity data accessible through GBIF in scientific research and decision making

In the current strategic period, GBIF focuses on increasing the relevance and diversifying the uptake of GBIF-mediated data for scientific research (priority area 1). This requires capacity development through partnerships with academia and higher education, including through supporting thematic research communities with limited previous knowledge of GBIF. In addition, GBIF seeks to develop the capacity to use data to support policy responses addressing societal challenges around planetary change. This includes contributing to local, national, regional, and global biodiversity-related goals and indicators, and partnering to support the application of data in policy-relevant information tools and products (priority area 2).

Progress towards this objective will be seen in the breadth and representativeness of the growing body of scientific literature that cites the use of GBIF-mediated data.  GBIF maintains an ongoing literature tracking programme, which identifies research uses and citations, and groups these into thematic research areas. Literature tracking can highlight geographic gaps and targets for development in GBIF’s research user communities. These research uses ultimately depend on capacity at the level of individual scientists and students involved, but are greatly facilitated by the development of methodologies and norms for using open biodiversity data within a research field and the academic institutions involved.

Progress in capacity to use GBIF-mediated data for policy objectives may be tracked through examples of uptake in national policy reports, regulations and indicators, including those provided for implementation of global biodiversity-related conventions, although this is likely to be less quantitative than metrics from research citations. 

Based on thematic priorities, as GBIF works more closely with research communities to develop areas of scientific relevance for open biodiversity data (such as in human health, freshwater ecology, and soil biodiversity, among others), capacity development actions should target the development of necessary skills at the level of students and researchers. Such actions should also address the known geographic gaps in the user community, and serve to promote more global engagement of users in line with GBIF’s global scope and vision. While guidance and training materials on accessing GBIF mediated data for a variety of use cases are available, it is beyond GBIF’s scope to provide training in all the underlying data literacy skills needed for research use of open biodiversity data. 

Participant nodes support user communities through a variety of capacity development actions, often in direct partnership with academic institutions that use GBIF within teaching at various levels. Nodes also play a role in supporting data flows into biodiversity-related reporting processes and other decisions. Capacity development actions to support the nodes in their role in coordinating national networks and engaging with user communities both at the research and policy levels will continue to help with the scalability of approaches.
