[[conclusion]]
== Conclusion

This framework updates the 2015 https://doi.org/10.35035/doc-qpxw-n868[GBIF Capacity Enhancement Framework^] and serves as an inclusive guide for GBIF’s capacity development action over the five years of the Strategic Framework 2023-2027. Capacity development plays an essential role in GBIF, and this framework sets out adaptable tools, approaches and indicators to enable us to scale our activities to meet emerging opportunities and keep track of their impact.

The GBIF Secretariat will apply this framework in its continuing efforts to support node development through collaboration, to design and implement capacity development programmes, to support the community of practice, and to roll out the training strategy and associated learning resources. Participant nodes and other partners are encouraged to use this framework when designing capacity enhancement activities, both within their own context and when defining collaborations with external partners. Potential partners are encouraged to evaluate how the approach described in this framework could align with their priorities and principles, when considering potential capacity enhancement collaboration with the GBIF network. The Community and Capacity team at the GBIF Secretariat is available to provide further information on this framework, how to put it into practice and potential avenues for collaboration. 

This framework is shared as a living digital document open for comment and suggested revisions from the GBIF community at any time. This framework will be reviewed for the next strategic planning period starting 2027.
