== Introduction

The framework acts as a roadmap for the Secretariat, Participant nodes, and the wider GBIF community, directing capacity development efforts throughout the strategic period spanning from 2023 to 2027. GBIF aims for - and anticipates - a scaling up of capacity development work within this period. The tools and approaches presented here are adaptable to enable the implementation of this framework in line with the opportunities arising during this period.  

The https://www.cbd.int/gbf[Kunming-Montreal Global Biodiversity Framework^] includes https://www.cbd.int/gbf/targets/[targets for 2030^] that directly address the need to make data, information and knowledge for decision-making available (target 21), as well as the need for strengthened capacity-building and development, technology transfer, and technical and scientific cooperation (target 20). In addition, the https://www.unesco.org/en/open-science/about[UNESCO Recommendation on Open Science^] provides an international framework for open science policy and practice, aiming to “reduce technological and knowledge divides between and within countries”. The recommendation asks UNESCO Member States to invest in infrastructure for open science, as well as, in training, education, digital literacy and capacity building to support open science. These two instruments provide an important global policy context for expanding capacity development actions through GBIF. 

GBIF’s capacity development work is framed under two core objectives: developing the capacity to mobilize biodiversity data through GBIF and developing the capacity to use GBIF-mediated biodiversity data. 

GBIF seeks to embed capacity on nested levels from individual, to institutional, national and  regional scales, helping to strengthen the network as a whole. Defined goals and indicators will help GBIF to monitor progress on each level, guiding further implementation. This monitoring, together with ongoing needs assessment processes, periodic evaluation of capacity development programmes and actions, forms the basis of reporting to the community on progress made. 

The wide array of capacity development tools and approaches in use across the GBIF community are broadly categorized as: support for node development through collaboration; capacity development programmes; further development of the community of practice; and training and learning resources. Together, these empower a broad community of experts to contribute to capacity development goals, and enable the flow of expertise between the capacity development levels, supporting the necessary scaling up of capacity development work and community growth over the current strategic period.

GBIF’s capacity development activities embody its agreed https://www.gbif.org/strategic-plan[values^], contributing to trust and transparency, collaboration and collective benefit, diversity and inclusiveness, innovation, and integrity.  Embedding these values in capacity development activities ensures that growth in the community engaged through this work builds on the community’s existing strengths that have proven a solid foundation for capacity development to date. 
